# Generated by Django 4.2.3 on 2023-07-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='okabc', max_length=50),
        ),
    ]
